all:
  vars:
    ansible_connection: ssh
    ansible_user: confluent
    ansible_become: true
    ansible_ssh_private_key_file: /home/confluent/.ssh/id_rsa
zookeeper:
  hosts:
    zk1:
      zookeeper_id: 1
    zk2:
      zookeeper_id: 2
    zk3:
      zookeeper_id: 3
kafka_broker:
  hosts:
    b1:
    b2:
    b3:
control_center:
  hosts:
    ccc:
